transitmatters/t-performance-dash

src/constants.js

adding Wollaston station to the Red Line

Updated constants.js

---

package-lock.json
package.json
public/index.html
server/chalicelib/data_funcs.py
src/AlertBar.js
src/App.css
src/App.js
src/LegendAlerts.js
src/Select.js
src/StationConfiguration.js
src/constants.js
src/line.js
src/stations.js

Merging Ian's style updates into master.

Ian style updates

---

Pipfile
Pipfile.lock
deploy.sh
server/app.py
server/chalicelib/MbtaApi.py
server/chalicelib/MbtaPerformanceAPI.py
server/chalicelib/data_funcs.py
server/chalicelib/secrets.py
src/App.js
src/StationConfiguration.js
src/constants.js
src/stations.js

Not sure what's in this branch, really...

GL updates

---

.github/workflows/lint.yml
README.md

Fixed typo in javascript job

---

.github/workflows/lint.yml
.gitignore
README.md
package.json
server/Pipfile

CI now uses npm to lint both frontend and backend instead of just the former

Changed CI to mimic manual linting

---

.github/workflows/deploy.yml
README.md

Creates new Github Actions workflow that runs `deploy.sh` every time code is merged into master

Add Continous Deployment to AWS Lambda

---

deploy.sh

More info here: https://github.com/aws/serverless-application-model/issues/71

deploy.sh no longer fails if if stack exists

---

public/index.html
src/App.css
src/App.js

Show beta tag only on dashboard-beta or localhost

---

src/line.js

Addresses #29 
I think the new behavior is more intuitive, but someone should verify. 
The new nit to pick is that there's a bias towards points with smaller x values, but I don't think fixing that is as high a priority.

Add custom tooltip positioner to center on data value

---

server/.chalice/policy.json
server/app.py
server/chalicelib/MbtaPerformanceAPI.py
server/chalicelib/data_funcs.py
server/chalicelib/s3.py
server/chalicelib/s3_alerts.py

- Download MBTA alerts across all routes every morning
- Use our storage instead of MBTA-performance for quick retrieval

Download and store alerts every morning for all lines

---

server/chalicelib/aggregation.py
server/chalicelib/s3.py
server/chalicelib/s3_historical.py

A bit of an update to s3_historical functions to accommodate them handling a date-range and having maybe thousands of entities from multiple service days.
Might still be more to do to improve performance, but this should help at least somewhat.

Speed up agg

---

docs/README.md

I'm a grade-A fool for not including this before. Sorry!

Add deployment documentation to README.md

---

src/App.js
src/line.js

Addresses #2 with some plugins. Hopefully it's not too ugly.
I also hard-coded the alerts timeframe, since traveltimes don't always line up (esp. with historical trip-id issues)
However.
This also introduces an error when switching out of multi-day mode into single-day mode.
Perhaps @mathcolo has some tricks to help?

Whole day x

---

server/chalicelib/data_funcs.py
server/chalicelib/s3_historical.py
src/StationConfiguration.js
src/line.js

Still testing this, but looks okay so far in Firefox, Safari, and iOS Safari.
I'll open the Chrome can of worms when I feel ready to handle oblivion
(Fixes https://github.com/transitmatters/t-performance-dash/issues/77)

Fix all JS console warnings/errors

---

src/App.js

Fix https://github.com/transitmatters/t-performance-dash/issues/69
Add an AbortController array, so new fetches signal all existing fetches first.

Aggregation: Cancel existing requests on config change

---

src/constants.js

2 things:
- I picked maybe the worst possible days for the T. Do we want to be less harsh?
- I added a tiny bit of context as to why these days are interesting in the picker, which I find useful, but maybe it's too heavy-handed?

Update presets March 2021

---

public/index.html
src/index.css

Add version 2.0 to footer

---

.github/workflows/deploy_beta.yml

This change will allow us to test CD-related changes by pushing to a `beta` branch on the upstream repo - the action will pick up any changes made on this branch and automatically deploy them to the beta site

Added GH Action to deploy to beta site

---

.github/workflows/deploy_beta.yml
deploy.sh

Tested here: https://github.com/transitmatters/t-performance-dash/actions/runs/869306247

Fixed git fetch for shallow CD repo

---

src/App.js
src/constants.js
src/stations.js

Slowly paving the way for bus.
also note: green line is now east/westbound instead of north/south.
(perhaps we reconsider once GLX opens?)

flexible direction words

---

src/constants.js

removing & adding stations after b branch consolidation

changing stations

---

src/constants.js

after testing in beta, adding new stations to GL

updating gl stations

---

package-lock.json
package.json
public/index.html
src/App.js

The time has come.
NOTE: ⚠️ This is against `bus-staging`

Switch from Google Analytics to GoatCounter

---

public/index.html
src/App.js

Fix loading issues with goatcounter.
many further refinements are possible, but it's past midnight.

debug goatcounter loading

---

.github/workflows/lint.yml

Updated lint action to use npm ci

---

src/App.js

h/t @crschmidt 
Recreation of #112 with an additional comment

Improve local development API path code

---

src/charts/SelectableCharts.js
src/charts/line.js

keep yrange consistent on toggleable charts

---

src/slowzones/SlowZoneNav.tsx
src/slowzones/SlowZones.tsx

- Adds deep linking for slow-zones
- Isn't the prettiest thing I've ever written, but it works
- A test URL https://dashboard-beta.transitmatters.org/slowzones?chartView=xrange&startDate=2021-04-24&selectedLines=Red%2COrange
- Closes #177

Add Deep Linking for Slowzones

---

package-lock.json
package.json
src/slowzones/SlowZones.tsx
src/slowzones/formattingUtils.ts
src/slowzones/types.ts
tsconfig.json

- Sorts slow zones by `order` of station id per line
- Runs `prettier` on a few files

Sort Slowzones

---

package-lock.json
package.json
src/App.css
src/ChartSets.js
src/OpenSource.js
src/charts/Legend.js
src/charts/SelectableCharts.js
src/charts/download.js
src/charts/line.js

Addresses #9 
Apologies to @mathcolo who didn't want a library- There was extra messiness there that I'd rather just leave under the rug (this was complicated enough already)
These filenames are a bit obnoxious, but I can't think of many better ideas.
Oh! The icon is borrowed from iconoir (MIT license). Do I need to cite?

CSV download links

---

src/App.js
src/analytics.ts
src/constants.ts
src/slowzones/SlowZones.tsx

- Add goatcounter to slow zones page
- Factor goatcounter and some constants out

Add goatcounter to slow zones

---

public/index.html

Also the feedback email subject since we have multiple dashboards now

Updated blog link

---

src/constants.ts
src/ui/ProgressBar.js

bus and rapid data already synced to backend.
(i wish this were more automate-able...)

May Bus update

---

src/slowzones/formattingUtils.ts

Looks like this line really expects a function and to ignore ts errors

Using function and ignoring ts

---

src/constants.ts

we forgot Wollaston

---

src/slowzones/SlowZones.tsx
src/slowzones/formattingUtils.ts

- Minimum slowzone length is 4 days not 3
- Algorithm improvements aren't really in the works anymore
- I have updated the title of the line graph to hopefully eliminate much of the confusion around it.

update line graph title and faq

---

next.config.js
package-lock.json
package.json
pages/SingleDayLineChart.tsx
pages/Title.tsx
pages/_app.tsx
pages/constants.ts
pages/index.tsx
pages/types/dataPoints.ts
tailwind.config.js
tsconfig.json

[v4 DEV] A working chart in ChartJs 3.9.1

---

.eslintrc.js
components/Layout.tsx
components/alerts/AlertBar.tsx
components/dashboard/charts/Legend.tsx
components/dashboard/charts/SingleDayLineChart.tsx
components/slowzones/SlowZonesContainer.tsx
components/slowzones/charts/LineSegments.tsx
components/slowzones/charts/TotalSlowTime.tsx
docs/README.md
package.json
pages/_app.tsx
pages/api/headways.ts
pages/api/hello.ts
pages/index.tsx
pages/slowzones.tsx

Adding another eslint rule I noticed would help keep our code clean

[v4 DEV] Import order rules

---

components/Navbar.tsx
components/inputs/Select.tsx
components/utils/ActiveLink.tsx
pages/index.tsx
src/StationConfiguration.js
src/index.js
src/stations.js
tailwind.config.js
types/inputs.ts
types/stations.ts
utils/constants.ts
utils/stations.json
utils/stations.ts

Creates select boxes with tailwind UI styling
Makes some utils around showing a list of stations for a line
**Issues:**
- I can't quite get dynamic colors with tailwind/next rendering of classnames

[v4 DEV] Select box with Tailwind

---

app/layout.tsx
app/page.tsx
app/slowzones/page.tsx
tailwind.config.js

- Adds `app` folder to tailwind config

Fix tailwind config

---

README.md
package-lock.json
server/poetry.lock

Dependency fixin

---

.github/CODEOWNERS

I've been working on this for a while now, would like to be added to the codeowners

Adding Devin to codeowners

---

package-lock.json
package.json

Fixing up the package.json and bumping what versions are available.
- Bumps everything to the latest
- Requires 18.6 or above since there was a vuln in 18.5 (just to be safe, shouldn't really change anything)
- Sets the package json to `4.0.0`

[v4 DEV] Bumping dependencies, and fixing package.json

---

src/slowzones/SlowZones.tsx
src/slowzones/formattingUtils.ts

This will remove the orange line shutdown-related emoji, and change the line graph description for the backend changes.

Ol cleanup

---

components/slowzones/charts/TotalSlowTime.tsx
components/widgets/BasicDataWidgetItem.tsx
components/widgets/Widget.tsx
components/widgets/internal/BasicWidgetDataLayout.tsx
pages/index.tsx
pages/slowzones/page.tsx

- Adds an initial Slow Zone widget
- Adds a new `internal` layout component that doesn't have shadow / etc to use with more complex widgets

Initial Slow Zone Widget

---

.vscode/settings.json
components/Dropdowns/LineSelector.tsx
components/Dropdowns/LineSelectorStyle.tsx
components/Dropdowns/SectionSelector.tsx
components/general/BottomNavBar.tsx
components/utils/Dropdown.tsx
constants/colors.ts
constants/sections.ts
pages/index.tsx
public/Icons/Components/SelectedLineIndicator.svg
src/App.css
styles/globals.css
tailwind.config.js

Add Section Selector

---

components/general/BottomNavBar.tsx
components/general/DataPageSelection.module.css
components/general/DataPageSelection.tsx
components/widgets/BasicDataWidgetItem.tsx
components/widgets/HomescreenWidgetTitle.tsx
package-lock.json
package.json
tsconfig.json

* Add data Page Selection to bottom nav bar
* Add mini-css-extended-plugin to dependencies - it's needed to write custom css I believe.
* The selector is a little messy, but I don't love it overall so will probably redo it eventually. Just need something so we can get navigation set up.

Add Data Page Selection

---

.babelrc
components/Navbar.tsx
components/general/BottomNavBar.tsx
components/widgets/HomescreenWidgetTitle.tsx
next.config.js
package-lock.json
package.json

We were getting a bunch of warnings like:
`Warning: ExploreArrow: Support for defaultProps will be removed from function components in a future major release. Use JavaScript default parameters instead.`.
I had previously set up bit of a weird way to import svgs. Cleaned it up to use `svgr webpack`

Fix SVG Loading

---

.github/workflows/deploy.yml
.github/workflows/lint.yml
components/widgets/HeadwaysWidget.tsx
pages/index.tsx
server/app.py
utils/date.ts

Added a basic headways widget with real data
Updated travel times to show a real number (real-ish)

[v4 dev] Adding a basic headways widget

---

src/slowzones/SlowZones.tsx

Temporary disclaimer about slow zone calculation changes.

Add a disclaimer to communicate Slow Zone changes

---

api/datadashboard.ts
components/dashboard/charts/SingleDayLineChart.tsx
components/dashboard/charts/Title.tsx
components/general/DataPageSelection.tsx
components/widgets/DwellsWidget.tsx
package-lock.json
package.json
pages/[line]/index.tsx
types/charts.ts
types/lines.ts
utils/constants.ts
utils/stations.json
utils/stations.ts

Adding a dwells widget to the home page
Shrinks https://github.com/transitmatters/t-performance-dash/pull/330 a little as a result

Adding a dwells widget

---

common/api/datadashboard.ts
common/components/charts/AggregateLineChart.tsx
common/components/charts/SingleDayLineChart.tsx
common/components/inputs/DateSelector.tsx
common/components/inputs/NativeDateInput.tsx
common/components/widgets/internal/BasicWidgetDataLayout.tsx
common/types/api.ts
common/types/lines.ts
common/types/router.ts
common/utils/date.ts
common/utils/router.tsx
common/utils/stations.ts
modules/dashboard/DataPageHeader.tsx
modules/dwells/DwellsDetails.tsx
modules/dwells/DwellsWidget.tsx
modules/dwells/charts/DwellsSingleChart.tsx
modules/headways/HeadwaysDetails.tsx
modules/headways/HeadwaysWidget.tsx
modules/headways/charts/HeadwaysSingleChart.tsx
modules/navigation/mobile/SecondaryNavBar.tsx
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/traveltimes/TravelTimesWidget.tsx
modules/traveltimes/charts/TravelTimesSingleChart.tsx

Uses the real date from the selector and the url bar. Allows deep linking to a specific date

[v4] Real date selection

---

common/api/datadashboard.ts
common/utils/slowZoneUtils.ts
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx

- Adds in some real calculations for the SZ widgets

Add Slow Zone data

---

common/utils/router.tsx
modules/navigation/desktop/SideNavBar.tsx

When clicking on a different line, keep the query params

Adding query params to routing

---

.flake8
.vscode/settings.json
server/app.py
server/bus/bus2train.py
server/bus/compare_manifest.py
server/bus/gtfs_archive.py
server/bus/manifest.py
server/chalicelib/MbtaPerformanceAPI.py
server/chalicelib/aggregation.py
server/chalicelib/data_funcs.py
server/chalicelib/parallel.py
server/chalicelib/s3.py
server/chalicelib/s3_historical.py
server/poetry.lock
server/pyproject.toml
server/rapid/process_events.py
server/refill_alerts.py

Updating all server deps to latest
Adding `black` for formatting consistency
Tagging @austinjpaul to make sure this should all be okay
All python changes are black applying formatting consistency

Updating server deps for v4

---

server/chalicelib/aggregation.py

I realize this change would ideally wait for v4, but I want to start populating an aggregate database and it would be very useful to have these numbers in it as i load it up.

Add 10th and 90th percentiles to backend

---

common/components/inputs/DateSelector.tsx
common/components/inputs/NativeDateInput.tsx
common/types/lines.ts
common/types/router.ts
common/utils/router.tsx
modules/dashboard/DataPageHeader.tsx
modules/navigation/mobile/SecondaryNavBar.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/traveltimes/charts/TravelTimesAggregateChart.tsx

Got the bare bones basics for aggregates working
did some work to get endDate to be treated right (also some work to prevent `line` from being unset for a second at first load)

[v4] Got basic aggregates working

---

common/components/inputs/DateSelector.tsx
common/components/inputs/NativeDateInput.tsx
common/utils/router.tsx
modules/navigation/desktop/DataPageTabs.tsx

- Fixes the query param issues / glitchiness seen here
https://user-images.githubusercontent.com/1361408/219959137-7fbd59bd-fb4e-4534-aff8-1e381e1b3ac4.mov

Fix Router

---

.env
.eslintrc.js
.github/workflows/deploy.yml
package-lock.json
package.json
src/index.js

As we get more and more traffic, might be nice to have a more detailed look at usage data
https://app.datadoghq.com/rum/application/1c18c845-9d82-40ba-b4bb-066ca95612be/overview/browser
Someone with admin perms, should add the two new secrets to github for deployment

Adding datadog rum

---

common/api/datadashboard.ts
common/layouts/Layout.tsx
common/utils/traveltimes.ts
modules/dwells/DwellsDetails.tsx
modules/dwells/DwellsWidget.tsx
modules/headways/HeadwaysDetails.tsx
modules/headways/HeadwaysWidget.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/traveltimes/TravelTimesWidget.tsx

Custom query is no longer needed
Also removed the round trip stuff. I think with station selector it will be easy enough to switch back and forth

Remove Custom Queries

---

common/components/inputs/Button.tsx
common/components/inputs/DateSelector.tsx
common/components/inputs/RangeButton.tsx
common/components/widgets/StationSelectorWidget.tsx
modules/dashboard/DataPageHeader.tsx
modules/navigation/mobile/LineSelectorMobile.tsx
modules/navigation/mobile/SecondaryNavBar.tsx
package-lock.json
package.json

Cleaning up the pickers and fixing some bugs with the datepicker, and mobile views
Fixes #369

[v4] Adding better pickers on desktop and mobile

---

package-lock.json
package.json

Updating node, typescript and lockfile

[v4] Updating packages for March 2023

---

common/components/inputs/DateSelection/DateConstants.ts
common/components/inputs/DateSelection/DatePickers.tsx
common/components/inputs/DateSelection/DateSelection.tsx
package-lock.json

[v4] Cleanup datepicker further

---

common/components/widgets/internal/BasicWidgetDataLayout.tsx
common/components/widgets/internal/Delta.tsx
common/types/basicWidgets.ts

1. Factor Delta of Widgets into a separate component. Functionally and visually identical to before.
2. Add MPH widget for upcoming Speed metric

Extract widget delta into separate component, and add MPH Widget

---

.eslintrc.js
common/components/accordion/Accordion.tsx
common/components/graphics/LoadingSpinner.tsx
common/components/inputs/DateSelection/DateSelection.tsx
modules/commute/alerts/AlertModal.tsx
modules/dashboard/DataPageHeader.tsx
modules/dashboard/TodaysCommute.tsx
modules/navigation/desktop/SideNavBar.tsx
modules/navigation/mobile/LineSelectorMobile.tsx
package.json

We didn't seem to be enforcing all eslint rules in ci for some reason, this should fix that

Better enforcing eslint

---

modules/headways/charts/HeadwaysAggregateChart.tsx
modules/headways/charts/HeadwaysHistogram.tsx
modules/headways/charts/HeadwaysSingleChart.tsx

Fixing Trains vs Buses on graphs

---

common/components/notices/BusDataNotice.tsx
common/components/notices/TerminusNotice.tsx
common/constants/stations.json
common/types/stations.ts
modules/dwells/DwellsDetails.tsx
modules/headways/HeadwaysDetails.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/tripexplorer/TripExplorer.tsx

Adding a notice for terminus stations

---

common/utils/emoji.ts
modules/commute/alerts/AlertBox.tsx
modules/commute/speed/Speed.tsx

Show a basic message when the line is shuttling and we don't have a MPH number to make it clear why
- Only shows when line is currently shuttling and we don't have a computed mph number
Hard to test when there isn't actually a shuttle running on a line at the time

[v4] Notice on Speed when shuttling

---

.github/CODEOWNERS

Updating `CODEOWNERS` so I start paying attention to PR emails 
Updated `CODEOWNERS` file
I tried it on every other repo first :wink:

Add Patrick to all codeowning, Removed Nathan from some codeowning

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/healthcheck.yml
.github/workflows/lint.yml

Updating the CI to match what we're doing in v4 with a matrix
Updates CI to use a dependency matrix

Updating CI for main

---

.github/labeler.yml
.github/workflows/label.yml

Adding an action to automatically label all PRs with useful labels based on what was changed

Adding labeler action

---

.github/labeler.yml
.github/workflows/label.yml

Didn't like Javascript/Python labels, preferred `frontend` / `backend`
Using `frontend` and `backend` labels

Labeler update

---

common/components/charts/AggregateLineChart.tsx
common/components/charts/SingleDayLineChart.tsx
common/utils/chartError.ts
modules/headways/charts/HeadwaysHistogram.tsx

V4 Missing Data Message on Charts

---

.github/workflows/deploy.yml
deploy.sh
server/.chalice/config.json
server/app.py
server/frontend-cfn.json
server/poetry.lock
server/pyproject.toml

#380 
Give us more detailed information about the performance of the app
- Adds datadog lambda tracing to chalice

Wire up Datadog Tracing

---

.eslintrc.js
modules/commute/alerts/DelayAlert.tsx
modules/navigation/SidebarTabs.tsx

Ensure we are using the right comparison types
Adds https://eslint.org/docs/latest/rules/eqeqeq to our rule list

Eslint === and !== rules

---

.github/labeler.yml
.github/workflows/label.yml
README.md

Adding an additional section to the labeler action (thanks @devinmatte) for documentation pieces, as we move to standardize labels (somewhat) across projects
New labeler config as well as some README updates - partially to test, partially for consistency with other repos
This PR itself shall serve as a test :smile:

Updated labeler action

---

modules/commute/alerts/AlertBox.tsx
modules/commute/alerts/AlertBoxInner.tsx
modules/commute/alerts/Alerts.tsx
modules/commute/speed/Speed.tsx

Did some usability testing, button colors were unclear.
Switched them so now:
Clickable = light background
Not clickable = dark background
**Before**
**After**
👀

Change button colors

---

common/constants/dates.ts
common/state/utils/dashboardUtils.ts
modules/ridership/RidershipWidget.tsx
modules/service/ServiceOverviewWrapper.tsx
modules/speed/SpeedOverviewWrapper.tsx

Make dates shorter on widgets by using M/D/YY format
A couple other minor style changes

Shorter Date and small style changes

---

common/components/charts/AggregateLineChart.tsx
common/components/charts/ChartBorder.tsx
common/components/charts/ChartDiv.tsx
common/components/charts/SingleDayLineChart.tsx
common/components/general/DownloadButton.tsx
modules/headways/charts/HeadwaysHistogram.tsx

Code Cleanup
Add div specific for charts
👀

Chart Divs

---

common/components/buttons/FeedbackButton.tsx
common/constants/pages.ts
common/layouts/Footer.tsx

Small change to footer and sidebar
- Feedback button links to sending email
- Removing Headways page option since we likely won't get that ready by v4
- Adding `join` to footer

Cleaning up footer and sidebar

---

common/constants/dashboardTabs.ts

- Closes #608 
System used to be last, now its first.
- very important to test 👍 🔥

feat: change position of system nav item

---

common/types/dataPoints.ts
common/utils/stations.ts
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesSegmentsWrapper.tsx
modules/slowzones/charts/LineSegments.tsx

fixes #489
- Adds a link to each line segment that opens in a new tab

Adding link to trips page for slowzone segment

---

pages/404.tsx

closes #648 
404 page was essentially empty
Add explanation and link to home
🤷‍♂️

improved 404 page

---

common/components/charts/AggregateLineChart.tsx
common/components/charts/SingleDayLineChart.tsx
modules/headways/charts/HeadwaysHistogram.tsx
modules/landing/charts/LandingPageChart.tsx
modules/ridership/RidershipGraph.tsx
modules/service/PercentageServiceGraph.tsx
modules/service/ServiceGraph.tsx
modules/slowzones/charts/LineSegments.tsx
modules/slowzones/charts/TotalSlowTime.tsx
modules/speed/SpeedGraph.tsx
pages/_app.tsx

Fix weird rendering issues with system pages
- Registers all plugins once globally
Only appears in prod bundle for some reason, so, deploy and hope

Register globally once chart js

---

common/components/notices/SameDayNotice.tsx
common/components/notices/TerminusNotice.tsx
modules/tripexplorer/TripExplorer.tsx

Day of data notice

---

server/app.py
server/chalicelib/secrets.py

See [v3 equivalent](https://github.com/transitmatters/t-performance-dash/pull/697) for info

[v4] hide secrets in healthcheck output

---

modules/landing/Landing.tsx

shrink hero animation to fit screen
(Also we had two of them overlapping somehow lol)
just trust me bro

fit hero animation into viewport

---

common/types/dataPoints.ts
common/utils/slowZoneUtils.ts
common/utils/time.tsx
modules/slowzones/SlowZonesSegmentsWrapper.tsx
modules/slowzones/SystemSlowZonesDetails.tsx
modules/slowzones/charts/LineSegments.tsx

- Adds missing full system slowzone graph as v3 has
- Adds new graph
- Removes datalabels
- Pull down this pr 💅

feat: add system wide slowzone segments

---

modules/ridership/RidershipWidget.tsx

bug: fix ridership chart config

---

server/.chalice/policy.json
server/app.py
server/chalicelib/dynamo.py
server/chalicelib/speed.py

Remove old `speed` api and other peripheral code.
There should be no noticeable changes.
Make sure speed + service still work.

Remove old unused speed code

---

common/components/widgets/StationSelectorWidget.tsx

Bug fix
The logic to deal with branches was breaking the lines which don't have branches.

Fix bug with selecting from stations.

---

common/api/hooks/slowzones.ts

Prevent double calls when date loads
- Adds enabled flag based on date existing

Prevent double calls when date loads

---

common/utils/middleware.ts
modules/slowzones/charts/LineSegments.tsx
package-lock.json
package.json

We need trailing slash to avoid a 302

Adding trailing slashes for redirects

---

common/api/slowzones.ts

Maybe call the right api route
Calling the API route the same as all other API routes

Fixing routing for api route

---

common/utils/constants.ts
deploy.sh
server/.chalice/config.json
server/frontend-cfn.json

Deploy to normal beta, not just v4 beta
- Copied over what felt missing from v3 deploy script
- Deploy to normal beta instead of v4 specific beta

Prepare deploy script for beta/prod deploy

---

common/components/buttons/DownloadButton.tsx

Color wasn't changing on hover anymore
Fixed color changing on hover for download button

Fix download button color

---

deploy.sh
server/cloudformation.json

Allow Datadog to be able to track down what line of code an error comes from in traces
- Add tags for git sha and repo url

Adding Datadog git tags

---

deploy.sh

I thought short sha was okay, I was wrong

Using full sha in ddog tags

---

modules/slowzones/charts/TotalSlowTime.tsx

[863] Set Total Slow Time minimum to zero

---

common/components/general/ButtonGroup.tsx
modules/service/PercentageServiceGraphWrapper.tsx
modules/slowzones/SystemSlowZonesDetails.tsx
modules/tripexplorer/BusTripGraphs.tsx
modules/tripexplorer/SubwayTripGraphs.tsx

Addresses #849 
https://github.com/transitmatters/t-performance-dash/assets/59891647/20019e8c-d0b2-4700-9583-d112601d0c6f

[849] Maps on Slow Zone page

---

common/constants/dates.ts
server/bus/gen_bus_data.sh
server/bus/setup_bus_input.sh
server/chalicelib/constants.py
server/chalicelib/data_funcs.py
server/rapid/gen_rapid_events.sh
server/rapid/setup_rapid_input.sh

Get bus data up to date
- Updates data update scripts slightly
- Adding bus data up to Oct 2023
- Adds strings in preparation for gobble

Updating bus data up to Oct 2023

---

common/api/slowzones.ts
common/types/dataPoints.ts
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/slowzones/SystemSlowZonesDetails.tsx

Merge before https://github.com/transitmatters/slow-zones/pull/41
Handles both current and new json formats for slowzones

Handle new updated_on date in json

---

common/components/graphics/ChartPlaceHolder.tsx
common/components/notices/ErrorNotice.tsx
server/app.py
server/chalicelib/s3_historical.py

Improve the experience when requests take too long

Improve error message on timedout requests

---

server/.chalice/config.json
server/poetry.lock
server/pyproject.toml

Hoping to get better tracing data for tracking down areas to improve timeouts
- Updates datadog extension and ddtrace

Updating tracing for ddog to get better data

---

server/rapid/gen_rapid_events.sh
server/rapid/setup_rapid_input.sh

2024 dataset for rapid transit data is available
- Adds 2024 dataset url
- Processed and uploaded the results for January 2024

Adding 2024 rapid transit dataset

---

server/app.py
server/chalicelib/aggregation.py
server/chalicelib/data_funcs.py
server/chalicelib/date_utils.py
server/chalicelib/dynamo.py
server/chalicelib/parallel.py
server/chalicelib/s3.py
server/chalicelib/s3_historical.py
server/chalicelib/speed.py

For data where we have monthly data, we don't need every date, but for gobble, we do. 
So we need a function that handles that for getting data from s3
- Replaces `month_range` with `s3_date_range`
- Adds a `MAX_MONTH_DATA_DATE` which is the date we have monthly data for
Test fetching data for many months in aggregate
Test fetching data from Jan 1 - present for buses via url params

Adding a function to properly handle gobble date ranges

---

common/constants/dates.ts
server/bus/gen_bus_data.sh
server/bus/setup_bus_input.sh
server/chalicelib/date_utils.py

Bus data up to 2024 is now available
- Updates bus data to support all the way through January 2024

Updating bus data to Jan 2024

---

common/constants/dates.ts
server/bus/setup_bus_input.sh
server/chalicelib/date_utils.py

Updating bus and rapid transit historical data for Feb 2024
- Updates Bus data for 2024-02-29
- Updates Rapid data for 2024-02-29

Update data to Feb 2024

---

modules/landing/LineButton.tsx

Fixes #964 
Fixing crash on home page link

Fix broken bus link

---

common/utils/array.ts
modules/service/ServiceGraph.tsx

Fix crashing overview

---

deploy.sh
server/cloudformation.json

Cache static assets to reduce loading times, and reduce our s3 costs
- Add cache headers to s3 uploads from next build

Cache static assets

---

common/components/graphics/styles/spinnerFillColor.ts
common/constants/baselines.ts
common/constants/colors.ts
common/constants/dashboardTabs.ts
common/constants/dates.ts
common/constants/ferry_constants/ferry_eastboston.json
common/constants/ferry_constants/ferry_f1.json
common/constants/ferry_constants/ferry_f4.json
common/constants/ferry_constants/ferry_f6.json
common/constants/ferry_constants/ferry_f7.json
common/constants/ferry_constants/ferry_lynn.json
common/constants/lines.ts
common/constants/pages.ts
common/constants/stations.ts
common/state/defaults/dateDefaults.ts
common/styles/general.ts
common/types/api.ts
common/types/lines.ts
common/types/router.ts
common/types/stations.ts
common/utils/router.tsx
tailwind.config.js

Breaking the new functionality for adding Ferry data into smaller chunks for review. Started with Types, Constants, and styles. 
Added Ferry manifests, made these by hand so they may not be 100% what they should be. Updated types to include the GTFS routes, and added stylings for the ferry section
At this point none of the changes are visible from the user side.

Added constants, types and styles for ferries

---

.github/workflows/build.yml
.github/workflows/deploy.yml
.github/workflows/label.yml
.github/workflows/lint.yml
common/constants/licenses/licenseInfos.json
deploy.sh
package-lock.json
package.json

Fix up some vulns
- Swap open source attribution library
- Update CI versions
- Fix deploy versioning

Fix CI versioning, and deploy, and vulns
