.github/workflows/lint.yml
README.md

- Added GitHub Actions workflow for linting Python files in `server/` and JS files in `src/` (note this will only run on Pull Requests)
- Added lint status badge to `README.md`

Added Python and Javascript linting

---

src/App.js
src/Title.js
src/constants.js
src/line.js

I've had a go at implementing one of the improved designs for the chart titles. I think the splitting it into smaller chunks helps readability, and I'm a fan of the added color for orientation. (My preferred option with a highlighted background is substantially more difficult to do in HTML canvas, since you have to draw the background color rectangles separately...)
I'm in no way a front-end dev, so let me know your thoughts, esp. if I've done something totally funky.  There are some issues with words overlapping on very small windows- resolving this might make things complicated at best, and infeasible at worst.
Anyway, I'm curious to hear others' thoughts on this approach...

Add color to station names in chart titles

---

src/constants.js

Our current presets have fallen outside of the 90-day MBTA-performance cutoff. Time to update them...

Update broken presets

---

.github/workflows/deploy.yml
deploy.sh
server/.chalice/config.json
server/app.py
server/frontend-cfn.json
src/App.js

This PR evolves the dashboard to take advantage of the chalice package's built-in stages (aka environments) in order to get dashboard-beta.transitmatters.org working.
`./deploy.sh` still works, but now `./deploy.sh beta` is an option too.

Add support for dashboard-beta.transitmatters.org

---

src/Legend.js
src/line.js

Addresses #28 
I'm opening this against main for public release, I think. lmk if I should be trialing this in the beta server first. (also, which branch is the beta version using?)

Make points colorblind-friendly and add purple for >100%

---

server/chalicelib/MbtaPerformanceAPI.py
server/chalicelib/aggregation.py
server/chalicelib/data_funcs.py
server/chalicelib/s3.py
server/chalicelib/s3_historical.py

Minimizing the number of API requests for aggregation by bunching them together (mbta api can take a week at a time) to improve performance.
This also paves the road for executing multiple s3 object downloads in parallel.
~~The code right now is a bit messy, and still has some bugs, but I'm pretty sure `headways` is working as intended, and I just messed up the copy/pasting for travel_times and dwells.~~ EDIT: known bugs have been addressed and code has been linted. Design might not be the best- I was aiming for quick implementation minimizing refactoring.

Multiday mbta api

---

server/app.py
server/chalicelib/data_funcs.py

I think @friendchris is right about this!
1. We need to do the 3:30am math for determining which alert day to use at request time
2. The job itself was already using transit days, since it was using @friendchris MbtaPerformanceAPI.py
3. That _still_ presents a problem for the job, because the job runs at 5am (or 6am on DST), not 3:31. So between 3:30 and 5am/6am, there will be a gap where it's the new transit day, but we haven't downloaded yet.
4. To fix #3, just use the API for today AND yesterday's "transit days".

Use 3:30-3:30 days when determining whether to query T API for alerts, and cron two days ago instead

---

server/chalicelib/s3_alerts.py

Some alerts didn't have proper route info... if that happens, the alert parsing was bailing out early. Example: https://dashboard.transitmatters.org/rapidtransit?config=Orange,70034,70024,2021-02-22
Might as well throw (ha) a try/except at the problem

Fix breakage when alerts are malformed

---

server/chalicelib/data_funcs.py

Over this weekend I downloaded alerts from the T as far back as they would go. That date is November 6, 2017! So I'm updating this logic to only use the live API for today and yesterday.

We have alerts cached back to November 6, 2017 now

---

public/index.html

I threw in the envelope 📩 instead of the rocket 🚀. Mailto goes to `labs@` with a simple, but generic subject. At the moment, displays the same on main and beta.
I like @androotubelli suggestion of trying this and seeing whether users actually use it.

Add feedback link in footer

---

server/chalicelib/aggregation.py

This will prevent only the NaN error when there's only 1 train reported. Perhaps we should handle NaNs more generally?
Also, maybe it makes sense to throw out any data points where only 1 train came that day, since it's almost guaranteed to be an outlier?
The .loc business is a bit more efficient than what we were doing before.

use population std to prevent NaN json error

---

src/Select.js
src/StationConfiguration.js

Fixes issue #76. This happens on `main`, so this PR is against main.
The station picker cannot deserialize station info from the URL right now, because we cannot match station indices based on objects—they're not the same. Have to compare stop names themselves instead.

[Short and sweet] Fix station picker deserialization

---

src/App.js
src/StationConfiguration.js
src/constants.js

Add an option to the presets for the April 2021 OL slow zone, with a dynamic end date that's always today.

Add northern OL preset April 2021

---

src/constants.js

Trailing comma in the date messes up queries.

Correct trailing comma in Orange Line Slowdown

---

server/chalicelib/s3_alerts.py

Automatic overnight alert pull was broken because `get_api_data` changed— quick fix! :-)

Fix s3_alerts.store_alerts to use new get_api_data argument order

---

server/app.py

The train tracker issue this morning reminded me that the dashboard needs a real health check. This checks to make sure the API key has a non-zero length, and that it can get alerts from S3. 500 error if a check fails, and a number output indicating which one.

Add backend healthcheck

---

.github/workflows/deploy.yml
.github/workflows/deploy_beta.yml
deploy.sh
docs/README.md
server/frontend-cfn.json

Deployments sometimes cause the backend to break because the API key isn't set automatically. It's now passed in through GitHub secrets into deploy.sh like it's supposed to be. Sorry this took so long @nathan-weinberg!!
Fixes https://github.com/transitmatters/t-performance-dash/issues/82

Set API key through deploy.sh

---

package.json
src/App.js
src/line.js

This has been a bit overdue- it should resolve #63 
Chart types are now separate, which should make adding a new chart type for buses and peak/off-peak stuff easier. 
Hopefully things are cleaner/more readable, but let me know if I've gone too far.
Major things include:
- turning our `Line` chart into two types: `SingleDayLine` and `AggregateLine`. Most common settings are factored out into defaults, and so each chart can have more specific logic built in. Git diff is making a mess of this, it might be easier to read just the final file.
- E.g for the above: the suggestedXRange logic was moved out of App.js and into each chart's axis settings (as an `afterDraw` function).
- There was a bug where picking a date range >8months and then quitting multi-day mode would leave you stuck with the …

Aggregation refactor

---

server/chalicelib/MbtaPerformanceAPI.py

This might could be improved later, but works for now.
Also switched requests so we can log the useful message from the server along with the 400 client error info. e.g. `{ "error": { "message": "Missing required query parameter: api_key" }}`

hotfix for dst

---

src/App.js
src/presets.js
src/ui/ProgressBar.css
src/ui/ProgressBar.js

I wanted this to be a "minor bug fix", and functionality-wise, it is. But it's structurally different enough that it probably warrants a separate review. Thanks, and sorry!
==========
ProgressBar now encapsulates its own "progress" state. This prevents everything in App from rerendering with the timer (since state was being updated). 
The `key` is used to tell React when to "refresh" the progress bar (i.e. on configuration change), which it does by mounting a brand new one. Visibility is controlled by presence or absence in the DOM instead of css.

Progress Bar refactor

---

src/presets.js

not using TODAY for OL because we will forget to update it in 8 days and it will break.

fix linter error

---

src/inputs/date.js

Fixing bug on iOS because apple decided html5 <input type=date>'s max: prop shouldn't do anything.
New version is currently deployed on beta if you have an iPhone and want to confirm.
(thanks @purcellif17 !!)

hotfix: force flatpickr for everyone

---

src/App.css
src/ChartSets.js
src/constants.js
src/presets.js
src/ui/notes.js

Adds disclaimer for current day's data which may be messy.
It turn out that the T's overnight processing doesn't clean up all the mess, so we may want to consider other approaches in addition to this.
This also won't handle the midnight-3am scenario without more complicated logic... I can add if desired.

add todayDiclaimer for messy day-of data

---

public/index.html
src/App.js

All of our other active apps do not have "TransitMatters" in the front of their tities, this PR does the same for Data Dashboard (yay standardization again)

Changed Window Header Title to match other TM Labs apps

---

src/App.css
src/slowzones/SlowZoneNav.tsx

⚠️ This PR's base is Seth's branch, not main!
~⚠️ Still need to test on mobile~
- Fix bar height weirdness with a line-height adjustment. It seems a property from bulma framework was causing this, not 100% sure though...
- Widen the "Total slow time" and "Line segments" labels by a tiny bit so they fit on one line
- In "Total slow time" mode, disable the slider and reduce opacity instead of making it disappear completely
(Fixes #171)

Slow zones CSS fixes

---

package-lock.json
package.json
src/App.css
src/App.js
src/charts/Title.js
src/constants.ts
src/index.js
src/inputs/date.js
src/react-app-env.d.ts
src/slowzones/SlowZoneNav.tsx
src/slowzones/SlowZones.tsx
src/slowzones/formattingUtils.ts
src/slowzones/types.ts
tsconfig.json

- Adds slow zone information at `/slowzones`
- Has two graphs, one for total "slow" time per day, and one for all slow zones.
- There is also a dropdown bar on the top right that allows you to save the charts as `png/jpg`
- You'll have to add `all_slow.json` to `public/static/slowzones` locally to test (let me know if you have any troubles)
- I'd love some input on design / copy
- I could add a date filter if needed. Right now I'm starting at 1/1/2021

Slow Zones

---

src/charts/line.js

Adding years to label the X-axis of our aggregate chart (so that screenshots on twitter can get full context).
[anyone can review-- i'm just picking people arbitrarily]

add year to xLabel in aggregate charts

---

server/bus/bus2train.py
server/bus/gen_bus_data.sh
server/bus/gen_latest_bus_data.sh
server/chalicelib/aggregation.py
server/chalicelib/parallel.py
server/chalicelib/s3.py
server/chalicelib/s3_historical.py
server/rapid/gen_rapid_events.sh
server/rapid/process_events.py
server/rapid/setup_rapid_input.sh
src/App.js
src/ui/ProgressBar.js

Per @crschmidt's suggestion, we can cut down on data loading overhead by switching to monthly data event files instead of daily.
- Increases displayable range from 8 months of data to 18 months. (30s being a hard cap on API timeout)
- Incorporates @friendchris's data ingestion [scripts](https://github.com/transitmatters/performancedashbackfill) into the repo (adjusted for monthly files and to match the bus upload scripts)
- Updates the bus data upload scripts to output monthly files.
I would encourage everyone to check this out on beta to make sure the new progress bar timing is accurate.
Heads up: While the lambda now serves data 50% faster, local development server is pretty slow, at least on my laptop. My guess is too much concurrency- a single api request is quick, but loading a page …

Switch to monthly event files

---

src/App.css
src/slowzones/SlowZones.tsx

Fixes a typo and adds some padding for mobile-friendliness to the FAQ

Fix Slowzone typo 

---

.eslintrc.js
.github/workflows/build.yml
.prettierrc.js
docs/README.md
package-lock.json
package.json
src/App.js
src/App.test.js
src/charts/Legend.js
src/charts/legend.css
src/inputs/date.js
src/slowzones/SlowZoneNav.tsx
src/slowzones/formattingUtils.ts

Okay, so eslint caused a build issue despite working fine with `npm start`
Two major things are different with this PR compared to the last one:
- The eslint parser now handles typescript explicitly
- There's a new CI job to ensure the code builds
By adding these two new parsers/plugins it threw a few more errors/warnings. Ignored some, fixed others:
- No explicit `any`, ignored for now
- No more `@ts-ignore`, if you need to have ts shut up, use `ts-expect-error` and describe why in the comment
- No use of `Function`. It offers no real typechecking

Eslint update round 2

---

.eslintrc.js
package-lock.json
package.json

We had discussed removing default exports, this adds the plugin to allow enforcement
I turned it off for now as it would require editing quite a few files, we can turn it on after a slow migration as to not cause a bunch of issues with builds

Adding eslint import plugin for future enforcement

---

src/charts/legend.css

in the css for the legend on the subway Travel Times and headways graphs, both `.legend-dot` and the on-time/percentage class selectors have the same precedence. when I load the page (chrome on linux), this results in the key all being colored with `#bbb`, since `.legend-dot` is apparently loaded later, which isn't really a helpful key.
this commit solves this naively by adding `!important` to the `background-color`s for the on-time/percentage classes, so they'll be used regardless of the order css files are loaded.

color subway travel and headway legends

---

src/stations.json

Looks like in the move to have this data be a json file, we lost Wollaston again

Adding back Wallaston again

---

src/slowzones/formattingUtils.ts

shifting y axis minimums can distort how line graphs are compared
since these graphs are always positive (negative time spent in slow zones sounds really cool actually), we can simply set the minimum y axis to 0, and graphs should be much more visually consistent (at least until we get negative slowzones)
This should resolve #216
Screenshot:

make slowzones line graphs always include zero

---

src/App.css
src/constants.ts
src/slowzones/SlowZones.tsx
src/slowzones/formattingUtils.ts
src/slowzones/types.ts

Marks shutdowns on the chart to make it clear that the slow zones didn't just disappear

Orange line shutdown notice

---

package-lock.json
package.json
src/App.css
src/constants.ts
src/slowzones/SlowZones.tsx
src/slowzones/formattingUtils.ts
src/slowzones/types.ts

- Vertical line on yesterday's date to help indicate which SZs are current vs fixed recently
- Caution icons to SZs created by the recent shutdown (by closing the range on the date comparison)
- Construction icons to the "shutdown six" slowzones that should have been fixed.
- Fixed line-chart bug where data points were not aligned with tick marks due to timezones.
- Fixed gantt bug where min and max didn't actually limit the chart range.

Slowzone frontend improvements

---

public/index.html
src/App.css

As the Slow Zones tracker (and the Data Dashboard generally) receive an enormous influx of traffic, we should at least try to convert some of those visits into donations for TM. I've added a very quick link to our org-wide `/donate` page affixed to the top-right of all DD pages that looks like this:
It works well on desktop and on modern mobile viewports (>350px).
_Test plan:_
Visit any page and verify that the new button takes you to the `/donate` page, in a new tab.

Donate button

---

public/index.html

...whoops. The button was occluded by the header graphic on small screens.

fix: Move the donate button above the hero logo in z-index

---

server/chalicelib/aggregation.py

Requesting historical data for August 2018, e.g. would not work because pandas decided to return an Index instead of a DateTimeIndex.
This should fix that by manually coercing it.
```
>>> cal = USFederalHolidayCalendar()
>>> cal.holidays(start=datetime.date(2021,8,1), end=datetime.date(2021,8,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
>>> cal.holidays(start=datetime.date(2020,8,1), end=datetime.date(2020,8,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
>>> cal.holidays(start=datetime.date(2019,8,1), end=datetime.date(2019,8,31))
DatetimeIndex([], dtype='datetime64[ns]', freq=None)
>>> cal.holidays(start=datetime.date(2018,8,1), end=datetime.date(2018,8,31))
Index([], dtype='object')
```

fix obscure pandas bug

---

.github/workflows/build.yml
.github/workflows/lint.yml
docs/README.md

Right now, the README badges display the status of the most recent workflow run, including those on PRs. This means that it sometimes appears that things are failing when they actually aren't. This PR adds a lint and build run to each push to `main` and updates the badges to only show workflows run against `main` so the badges reflect only the `main` branch.

Change badge display source workflows

---

src/slowzones/formattingUtils.ts

Fix for Issue #237 
Changed the links on the slowzones page to link to the current URL rather than always linking to production.

Slowzone links fix

---

src/inputs/date.tsx

Issue #121: The Flatpickr object was firing onChange for date selection even when the currently selected date was chosen.
This is because Flatpickr always fires onChange on selection of a date ([doc]( https://flatpickr.js.org/events/)). Our `DatePicker` object has a separate element for use on mobile `RegularDateInput` which does not have this issue. So I added logic only on the Flatpickr. Not sure if it would be more clear to do just do it on both or leave a comment explaining this in the code. lmk.

Prevent update on selection of same date

---

.github/workflows/healthcheck.yml
README.md
package.json
server/app.py
server/pyproject.toml

This is a quick and dirty CI implementation using the `/healthcheck` endpoint introduced in #88 
Very open to suggestions here - for example right now the job is running on PRs and merges to `main`, but we could also have it be an independent job that fires on a [schedule](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule) instead.

Add healthcheck to GitHub Actions

---

package-lock.json
server/poetry.lock
server/pyproject.toml

Basically, this forces Poetry to use Python 3.9 for the virtualenv, even if a newer version exists on the system
Currently running on Beta: https://dashboard-beta.transitmatters.org/

Force poetry to use Python 3.9

---

src/App.js
src/StationConfiguration.js

Issue #126 
**Issue:**
React router history was storing all of the current app state in the browser. This included all data points in any visualization shown.
**Fix:**
Changed history to only save configuration and error message.
**Other Changes:**
- I was having a hard time understanding the code which was dealing with history and updating the URL query parameters. If people don't think the changes I made are improvements, I'm happy to remove them.
- One change was to remove the trailing comma at the end of the links when there is no `end_date`. Like this one: `/rapidtransit?config=Red,70061,70067,2022-11-09,` will now be: `/rapidtransit?config=Red,70061,70067,2022-11-09`
- Another change was to not add any parameters to the URL Query when the form is not complete. I figured there is no …

reduce history memory

---

.gitignore
.vscode/extensions.json
.vscode/settings.json
README.md

Since we have a series of linting rules, it would be nice if the vscode experience was better out of the box. This sets some reasonable defaults for vscode and gives recommended extentions so that it's a quicker and more straightforward experiece to work on the repo

[v4] VSCode better out of the box

---

api/datadashboard.ts
app/layout.tsx
app/page.tsx
components/dashboard/charts/AggregateLineChart.tsx
components/dashboard/charts/SingleDayLineChart.tsx
components/dashboard/charts/SingleDayPage.tsx
components/inputs/DateInput.tsx
components/utils/Date.tsx
next.config.js
package-lock.json
package.json
src/charts/types.ts
types/api.ts
types/lines.ts
utils/constants.ts
utils/stations.ts

Added queries to get data for single day charts. Haven't used these technologies before, so feedback is more than welcome.
TanStack has default behavior to refetch all queries on page focus. This meant if you switched tabs, clicked on dev tools, etc. then the data will be fetched when you return to the site. I disabled this on the queries I added. Not sure if people agree with that. Might be worth discussing.
I also added React Queries Dev tools. Shows up as a little flower icon on the page when in development. It didn't end up helping me much with the bug I was working on but it seems useful. I'm fine with keeping or removing it.
One really cool thing with react queries I didn't know about was the queryKeys. Lets you define what causes the query to refetch. So I set it up that headways …

V4 single day fetch

---

README.md
package-lock.json
package.json

To avoid vulns in npm deps, just updating the lockfile and restricting us to supported Node versions only. We run the app as node 16.x so restricting to 14.x+ should be perfectly fine and should just ensure we don't add a dangerous or unsupported library
v4 is still decently far away, so we should maintain the current release
Should close a few dependabot vuln PRs https://github.com/transitmatters/t-performance-dash/pull/295

Bumping package-lock and node to avoid vulns

---

next.config.js
package.json
utils/constants.ts

Temporary work-around to get the build to work while sorting out typescript issues. As per: https://transitmatters.slack.com/archives/GSJ6F35DW/p1673839728818259 @mathcolo 
I set it up to use a separate command to prevent us from accidentally deploying a build to prod with this workaround.

Ignore TS Errors on build temporarily

---

tailwind.config.js

I added tailwind screen breakpoints to our config to make accessing them easier. Only added `sm` at first. This adds the remaining default breakpoints

Add all tailwind default breakpoints to custom config

---

next.config.js
server/app.py

We have set up [nextJS rewrites](https://nextjs.org/docs/api-reference/next.config.js/rewrites) to hit port 5000 on API requests.
Right now, our API has no prefix in the path, so any path can be an API request. When next JS sees a URL it doesn't recognize i.e. a [dynamic route](https://nextjs.org/docs/routing/dynamic-routes) or a page that should be a 404, it rewrites these pages to the API, which fails.
This change adds `api/` to all backend API routes to prevent that from happening, and changes the next config to send rewrites to `api/`. In the previous commit, we changed the frontend URLs for the new V4 dashboard.
These are 3 other possible solutions I considered but didn't use for various reasons:
1. Dynamically append `api` to URL in DEV
* Would need to track env variables in the …

Add api/ to backend app.py routes

---

.github/workflows/deploy.yml

This should deploy to dashboard-v4-beta.labs.transitmatters.org on merge but no promises

[v4] Make github actions for dashboard-v4 work hopefully

---

.github/workflows/deploy.yml

Issues with fetching were fixed manually. Don't want them to get overridden. Will add this back after that's fixed.

Temporarily disable v4 auto-deployments

---

common/utils/stations.ts
modules/dwells/DwellsDetails.tsx
modules/dwells/DwellsWidget.tsx
modules/headways/HeadwaysDetails.tsx
modules/headways/HeadwaysWidget.tsx
modules/navigation/desktop/SideNavBar.tsx
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/traveltimes/TravelTimesWidget.tsx

- Adds details to Headways and Dwells pages
- Adds more details to traveltimes
- Adds utils to clean up existing views code
- Cleans up existing widgets code
- Hides widgets for views that don't apply to them (buses, green line slow zone)

[v4] Fleshing out full details of all pages

---

deploy.sh
server/.chalice/config.json
server/frontend-cfn.json
src/constants.ts

We want DD, like RRE and NTT, to create its own DNS records as a part of deployment. I did some of this work in `dashboard-v4` but this brings it to `main`.
This is the first step in getting on-demand subdomains for different builds working and ready

Create DNS records as a part of deployment

---

common/components/inputs/DateSelector.tsx
common/utils/router.tsx

Set default date to be current date.
Three notes:
1) I didn't put the date in the URL. So if someone shares the link it will always be today. Makes sense to me but idk. Maybe if the user is on a data page then we should add the date? Just not on overview?
2) I think the whole router situation needs some work. Lots of type weirdness. I started getting into it then undid my changes because it was getting gross.
3) Small UI change: date format YYYY-MM-DD, changed to M/D/YY. Still need to update on mobile.

Default date selector to today

---

common/components/general/ButtonGroup.tsx
common/styles/general.ts
common/types/inputs.ts
modules/commute/alerts/Alerts.tsx
modules/dashboard/LineHealth.tsx
modules/dashboard/Overview.tsx
modules/dashboard/TodaysCommute.tsx

- Add date range selector to line health section of overview page. It is not functional yet, that's next.
- Minor alerts style changes in preparation for `speed` metric
- Refactor overview component into `LineHealth` and`TodaysCommute` components

Add line health date range (not functional)

---

.github/CODEOWNERS

Removing people who aren't actively working on V4 from the `CODEOWNERS` file.
Will remove this change when merging back into main, but I figured I would save you guys a few hundred emails
@mathcolo @friendchris @nathan-weinberg if any of you don't want to be removed lmk and I can add you back.

Remove some codeowners for v4

---

common/components/general/ButtonGroup.tsx
common/constants/dates.ts
common/utils/slowZoneUtils.ts
modules/ridership/RidershipDetails.tsx
modules/slowzones/charts/LineSegments.tsx

When a SZ "ends" yesterday, mark it as ongoing. I accidentally broke this a few days ago.

Fix segments view to show 'ongoing' SZs

---

.eslintrc.js
common/components/alerts/AlertFilter.ts
common/components/charts/SingleDayLineChart.tsx
common/components/charts/Title.tsx
modules/headways/charts/HeadwaysHistogram.tsx
modules/speed/SpeedGraph.tsx

Noticed there were some spots we could better enforce destructuring, turns out there's a default eslint rule for it
- Adds a new rule to eslint to warn on cases where destructuring makes sense (most will be autofixable by vscode or eslint cli)

Eslint `prefer-destructuring` rule

---

.eslintrc.js
common/components/alerts/AlertFilter.ts
common/components/charts/SingleDayLineChart.tsx
common/components/charts/Title.tsx
modules/headways/charts/HeadwaysHistogram.tsx
modules/speed/SpeedGraph.tsx

Ensure we don't have any unused props on components
- Adds `react/no-unused-prop-types` as a warn
Remove all usage of a prop, ensure that the interface line is now a warning for that component

No unused props eslint rule

---

common/api/datadashboard.ts
common/api/hooks/alerts.ts
common/api/hooks/dwells.ts
common/api/hooks/headways.ts
common/api/hooks/ridership.ts
common/api/hooks/slowzones.ts
common/api/hooks/speed.ts
common/api/hooks/traveltimes.ts
common/api/ridership.ts
common/api/slowzones.ts
common/components/inputs/RadioList.tsx
common/components/inputs/ServiceDayPicker.tsx
common/constants/time.ts
modules/commute/alerts/Alerts.tsx
modules/commute/speed/Speed.tsx
modules/dwells/DwellsDetails.tsx
modules/dwells/DwellsWidget.tsx
modules/headways/HeadwaysDetails.tsx
modules/headways/HeadwaysWidget.tsx
modules/ridership/RidershipDetails.tsx
modules/ridership/RidershipWidget.tsx
modules/ridership/charts/TphChart.tsx
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/speed/SpeedWidget.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/traveltimes/TravelTimesWidget.tsx

We want to reduce API calls, especially when data has not changed since last fetch
- Moves API calls into reusable hooks and defaults reasonable staleTimes
- Adds the ridership dayselector

API Cleanup and Ridership fixes

---

common/components/widgets/StationSelectorWidget.tsx
common/utils/stations.ts
modules/navigation/LineSelection.tsx

Two small bug fixes. 
1) this [function ](https://github.com/transitmatters/t-performance-dash/blame/f2edac4e9da5e21730cfe794e15f210dab925602/common/utils/stations.ts#L87-L89) was only set up to work for subway stops, not buses.
2) When selecting the currently selected line, nothing happened. The intended behavior is to return to the `today` page
Added `busStations` to code that retrieves parentStationIds (function mentioned above).
Add code to trigger onChange() code for line selection tabs when button is clicked.
1) Go to any page besides `today` and click on the currently selcted line - should return you to `today` page.
2) go to `buses > headways` then `buses > travel times` then back to `buses  > headways` and there will be no issue. Try this on the previous PR (currently live at the …

two small bugs

---

common/api/datadashboard.ts
common/types/api.ts
modules/tripexplorer/BusTripGraphs.tsx
modules/tripexplorer/SubwayTripGraphs.tsx
modules/tripexplorer/TripExplorer.tsx
modules/tripexplorer/TripGraphs.tsx

fixes #452 
1. Main issue is that the trip explorer was not getting passed the `busRoute`. Fixed that
2. We also had no way to differentiate between bus and subway in `useCustomQueries` so I reworked that to take `BusOrSubway` as a parameter so we're not searching for non-existent bus dwell data.
3. Separated bus and subway trip graphs into two components.
Go to bus trip explorer page without `from`/`to` in the URL. This didn't work previously, now it does.

Fix Bus trip explorer page

---

README.md
package-lock.json
package.json

We have an open PR for https://github.com/transitmatters/t-performance-dash/pull/385
Although we're working on v4, we're probably going to keep an instance of v3 running for a little bit at launch, and, it's deployed today, so we should ensure there aren't any easily fixed vulnerabilities
- Bumps minimum node version to be accurate (lock is generated with node 16.x, and CI runs on 16.x, we should require 16.x)
- Fixes placement of a dev dep
- Does basic lock updates and `audit fix`

Updating package.json/lock to satisfy dependabot

---

modules/commute/alerts/AlertUtils.ts
modules/commute/alerts/DelayAlert.tsx
modules/commute/alerts/ShuttleAlert.tsx
modules/commute/alerts/SuspensionAlert.tsx

Reflects the reality, that `stations` can be a list of `(Station | undefined)[]`. We probably should ensure that can't happen, but, in the meantime, that is the reality and we need to handle it

Station can sometimes be undefined

---

server/poetry.lock
server/pyproject.toml

Updating python deps up to latest, along with https://github.com/transitmatters/slow-zones/pull/26 and https://github.com/transitmatters/data-ingestion/pull/9
Updates packages with new minor or patch updates, avoid major releases (see https://github.com/transitmatters/t-performance-dash/pull/451)

Updating python deps for April 2023

---

common/components/inputs/StationSelector.tsx
common/utils/stations.ts

When selecting a `to` station in the station selector, the `from` station disappears (and vice versa). Can be confusing and removing items from a list without explanation is typically bad UX.
The greyed out station can be a good anchor to figure out where you are. Also it is more clear why it is missing. If you aren't paying attention and are trying to select the same station and it is missing, that can be disorienting.
Make station disabled rather than not showing it.
Select stations

Station Selector UX change

---

.eslintrc.js
common/components/general/Device/index.tsx
modules/dashboard/Overview.tsx
modules/dashboard/TodayContainer.tsx
modules/dwells/DwellsDetails.tsx
modules/headways/HeadwaysDetails.tsx
modules/ridership/RidershipDetails.tsx
modules/ridership/RidershipWidget.tsx
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/slowzones/map/DirectionIndicator.tsx
modules/slowzones/map/SlowSegmentLabel.tsx
modules/slowzones/map/SlowZonesTooltip.tsx
modules/speed/SpeedDetails.tsx
modules/traveltimes/TravelTimesDetails.tsx
pages/[line]/dwells.tsx
pages/[line]/index.tsx
pages/[line]/overview.tsx
pages/[line]/ridership.tsx
pages/[line]/slowzones.tsx
pages/[line]/speed.tsx
pages/[line]/traveltimes.tsx
pages/[line]/trips/dwells.tsx
pages/[line]/trips/headways.tsx
pages/[line]/trips/traveltimes.tsx

We had a few spots on inconsistent named exports
- Adds rule to prefer named exports
- Excludes `pages` code since they need defaults

Eslint - Prefer named exports

---

server/app.py
server/chalicelib/data_funcs.py
server/chalicelib/dynamo.py
server/chalicelib/ridership.py
server/chalicelib/service_levels.py
server/poetry.lock
server/pyproject.toml
server/scripts/update_speed_restrictions.py
server/scripts/update_stations.py

For the Service and Ridership pages and related widgets, we want to use the latest data that we've begun ingesting into dynamoDB over in the [`data-ingestion`](https://github.com/transitmatters/data-ingestion) repo.
This PR adds two new API routes that query the `TripCounts` and `Ridership` tables:
Accepts `start_date`, `end_date`, and `route_id` GET params and returns an object with by-day trip counts as a list of ints. Because it returns an entry for every date, I figure we can omit those date strings to save bytes on the wire and recover that list on the client from `start_date` and `end_date` if necessary.
It also holds objects containing the by-hour trip counts (a list of 24 ints) for weekday, saturday, and sunday service. This should be everything we need to power this widget or …

API routes for service levels and ridership

---

common/components/inputs/DateSelection/DatePickers.tsx
pages/_document.tsx
styles/dashboard.css

https://github.com/transitmatters/t-performance-dash/issues/533
Match the current line color
Okay this is kinda hacky, but, there's no good interface to change the selected date color cleanly given the way flatpickr sets its styles. So, here's the function that pins a new classname onto the selected date to update the color

Setting selected datepicker color to match line

---

common/components/charts/AggregateLineChart.tsx
common/constants/colors.ts
common/types/charts.ts
modules/headways/charts/HeadwaysHistogram.tsx
modules/traveltimes/charts/TravelTimesAggregateChart.tsx
modules/tripexplorer/SubwayTripGraphs.tsx

Made some updates to the style
- The brighter blue background matches v3
- shrunk the weekday selector
- Tried out a step function. I think it makes sense because the slope doesn't really mean much on this graph.  Also, the fact that it's divided into half-hour increments means each increment is a distinct datapoint and showing a curved line between them is somewhat misleading.
Lmk what you think

some style changes

---

common/components/inputs/DateSelection/OverviewDateSelection.tsx
common/utils/router.tsx
modules/dashboard/HomescreenWidgetTitle.tsx
modules/navigation/BusSelection.tsx
modules/navigation/DashboardSelection.tsx
modules/navigation/LineSelection.tsx
modules/navigation/SidebarTabs.tsx
modules/navigation/utils/rangeTabUtils.ts

All of our nav was using button with onClick behavior, and not `<a>` tags or `<Link>` tags (nextJS <a> tag). This meant the browser was not treating these links as links and actions such as cmd + click to open in new tab did not work.
Also, changed some routing to be "shallow"  - this does not refresh the page, just updates the URL. Good for stuff like `Lines` page to keep your scroll position when updating date range.
Things like this URL showing up on hover only work with <a> tags:
I am most concerned that this will have an impact on global state management. Like saving date ranges across page sections. I didn't find any issues, but that would be a good place to look for edge cases.

convert to Next Links, add shallow routing

---

common/constants/dashboardTabs.ts
common/constants/pages.ts
common/utils/router.tsx
modules/dashboard/DesktopHeader.tsx
modules/navigation/BusNavMenu.tsx
modules/navigation/LineSelection.tsx
modules/navigation/SideNavigation.tsx
modules/navigation/SidebarTabs.tsx
modules/navigation/SubwayNavMenu.tsx
modules/navigation/SystemNavMenu.tsx
pages/system/index.tsx
pages/system/slowzones.tsx

- We want to get started on our `system` page!
- Adds a basic `index` and `slowzones` pages under `System`
- Changes some padding on the sidenav
|Before    | After |
| ----------- | ----------- |
|  ![Screen Shot 2023-05-13 at 1 01 44 PM](https://github.com/transitmatters/t-performance-dash/assets/1361408/61839a42-f742-4397-a517-7851d68716da) |  ![Screen Shot 2023-05-13 at 1 01 53 PM](https://github.com/transitmatters/t-performance-dash/assets/1361408/91fa7f4c-153b-4b67-8dad-37853c6b3298) |
- pull down this branch and run `npm install && npm start`

feat: basic system slowzones tab

---

modules/traveltimes/charts/TravelTimesAggregateChart.tsx

Our travel times agg charts were rerendering repeatedly, causing a flicker effect.
Fix the bug by moving data transformation into the `useMemo` call.
Also moved a couple other things inside the `useMemo` to reduce the dep array.
Lastely, updated the `id` so it is not the same for tt by date and tt by hour charts.
Go to aggregate trips page and adjust the date parameters repeatedly (take a few seconds between changing them). Do this on current V4 beta URL and this branch. This branch will not flicker.

Fix chart flicker

---

common/state/utils/dashboardUtils.ts
modules/dashboard/HomescreenWidgetTitle.tsx
modules/dashboard/WidgetTitle.tsx

We want dates on every graph for screenshotting purposes.
Closes #545

Add dates to widget titles

---

common/components/charts/Legend.tsx

The legend was taking up a bit too much space on mobile. We're trying to pack a lot in, so every pixel counts. Also, I think it looked a bit scattered.
Before / After
Look at various screen sizes

Shrink Legend

---

modules/slowzones/charts/LineSegments.tsx

Clicking the segment works in the dev bundle but doesn't seem to work on beta
- Splits object and removes TS ignores

Maybe fixing bug where link doesn't open with params

---

common/constants/pages.ts
common/state/dashboardConfig.ts
common/state/defaults/dashboardDefaults.ts
common/state/types/dashboardConfigTypes.ts
common/state/utils/dashboardUtils.ts
common/utils/router.tsx
modules/navigation/SystemNavMenu.tsx

We wanted to set up auto date filling on slow zones system page. Required some system tab setup.
Added logic to handle system tab in routing
Navigate around. I was running into an error going from `/` to `/system/slowzones`. It seemed to stop happening but I'm not convinced.

Add logic for system tab

---

common/components/controls/ControlPanel.tsx
common/components/controls/MobileControlPanel.tsx
common/layouts/DashboardLayout.tsx
modules/dashboard/MobileHeader.tsx

Closes #639 
also there was an issue with the page title logic on mobile. Seems when we added the slow zones tab we only updated the desktop header title logic. 
Still needed: `DatePresetConfig` logic for systems page.
Ideally there would only be one source of truth for mobile and desktop.... but not worth it at the moment imo.
**Before** (no controls and `•` before the title)
**After**
Controls and correct title.
Go to System > Slow zones page.

Fix system tab controls and title bug on mobile

---

server/frontend-cfn.json

We didn't have 404 routing set up correctly. There is still an issue where if you go to a valid `/<line-name>/<invalid-page>` page a client-side error is thrown. Probably a nextJS config issue.
Update cloudformation config to redirect to 404 page.
I manually deployed to beta stack, and it seems to be working fine: 
https://dashboard-v4-beta.labs.transitmatters.org/invalidLine/otherinvalidpage

Update Cloudformation config for 404 pages.

---

common/utils/router.tsx

Some pages that should be 404 were throwing errors. Mainly because the sidebar logic was trying to work with broken links. Updated sidebar logic to not throw errors when given incorrect pages.
For example, going to `/red/invalidPage` would show a client-side error message.
for line/busRoute selection - send links to default page (overview for rail, trips for bus).
Make sure invalid pages are not trying to save state.
Go to any invalid page. `/invalid`, `/<valid-line>/invalid`, `/system/invalid`, etc. and the sidebar _should_ show a reasonable value and all links still work.

Fix 404 bugs

---

common/utils/router.tsx

Fixes #681 
Changes from a `push` to a `replace` to stop polluting the history allowing logical back/forward nav
Click around links, and then use browser back nav one page at a time and make sure there isn't 2 entries per click, but at least 1

Using replace instead of push to fix back nav

---

.github/workflows/deploy.yml
README.md

Readme is out of date with the update from https://transitmatters.slack.com/archives/GSJ6F35DW/p1687385820382579
Update README and github action.
Should be good if the deploy succeeds.

Update README and GitHub action to clean up stale certificates

---

modules/dashboard/WidgetTitle.tsx

Closes #694 
- For single day trips, we don't have a `startDate`, so we need to check `date` as well.

feat: add dates to single day trips page

---

common/constants/dates.ts
common/constants/pages.ts
modules/dashboard/Today.tsx
modules/landing/LineSelectionLanding.tsx
modules/navigation/DesktopSideNavBar.tsx
modules/ridership/RidershipDetails.tsx
modules/ridership/RidershipGraph.tsx
modules/ridership/RidershipWidget.tsx
modules/service/ServiceGraph.tsx
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/slowzones/SystemSlowZonesDetails.tsx
modules/speed/SpeedGraph.tsx
modules/traveltimes/TravelTimesDetails.tsx
modules/tripexplorer/BusTripGraphs.tsx
modules/tripexplorer/SubwayTripGraphs.tsx

Some minor grammatical improvements, mostly around case (common nouns like "zone" and "hour" should not be capitalized).
Updated strings everywhere.
Load the page on local and browse around 👍

Sentence case everything

---

server/app.py
server/chalicelib/secrets.py

Exceptions can contain outbound http request URLs, which can expose API keys.
- Hide keys from public healthcheck output
1. Change the API key environment variable to an invalid value, causing the healthcheck to fail
2. The healthcheck output should contain the string `HIDDEN`.

[v3] hide secrets in healthcheck output

---

modules/service/ServiceDetails.tsx
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SystemSlowZonesDetails.tsx
modules/slowzones/charts/TotalSlowTime.tsx
modules/speed/SpeedDetailsWrapper.tsx

I forgot a few spots in https://github.com/transitmatters/t-performance-dash/pull/692
Don't tell nathan ;)

Forgot a few case adjustments

---

common/utils/time.tsx

There was a rounding bug with the widgets compared to the tooltips.  Caused by widgets receiving values in seconds, and tooltips receiving values in minutes, then converting to seconds.
This converts them back to seconds before creating the tooltip, so it will match the widgets. I think the core issue is that we want to round up seconds, and dayjs.duration() does not do that. So we need to round the seconds before creating a duration.
Since the tooltips are just values in seconds divided by 60, we can just multiply by 60.
The more complicated, but more accurate solution would probably be to convert all the charts to take seconds as the values. But this is good enough IMO.

rounding bug

---

common/components/charts/AggregateLineChart.tsx
common/components/charts/SingleDayLineChart.tsx
common/utils/time.tsx
modules/slowzones/charts/TotalSlowTime.tsx
modules/slowzones/map/SlowSegmentLabel.tsx

#706 and #365
- Ensures time labels are more consistent throughout the app

Updating time labels to be consistent across the app

---

common/components/inputs/DateSelection/DateSelection.tsx
common/constants/dates.ts

The rapid presets don't make sense for bus data #717 
I'm not 100% happy with these, but they're better than what we had before

Add bus date presets

---

common/components/buttons/DownloadButton.tsx
common/components/charts/AggregateLineChart.tsx
common/components/charts/SingleDayLineChart.tsx
common/components/general/WidgetCarousel.tsx
common/components/graphics/LoadingSpinner.tsx
common/components/widgets/StationSelectorWidget.tsx
modules/navigation/BusNavMenu.tsx
modules/navigation/BusSelection.tsx
modules/navigation/SideNavigation.tsx
modules/navigation/SidebarTabs.tsx
modules/navigation/SubwayNavMenu.tsx
modules/navigation/SystemNavMenu.tsx

Fixing accessibility issues according to lighthouse

---

common/utils/traveltimes.ts

#702 
If the value is 0, it reads as `false` in the if statement.
Changing to undefined check to provide real averages

Fix averages with 0s

---

modules/slowzones/charts/TotalSlowTime.tsx

Match the casing to chart title. (Total Slow Time -> Total slow time)
Remove line name when on line page.

small change

---

modules/slowzones/charts/TotalSlowTime.tsx

Fixing total slow time tooltip label

---

modules/dashboard/WidgetTitle.tsx
modules/tripexplorer/SubwayTripGraphs.tsx

- Noticed the travel time widget didn't have a subtitle and it looked a little off next to the other widgets that do.
- Adds travel time subtitle
| Before | After|
| ------------- | ------------- |
| ![Screen Shot 2023-07-09 at 3 29 25 PM](https://github.com/transitmatters/t-performance-dash/assets/1361408/96a51bd1-7855-4e2e-beeb-c74d965b5565) | ![Screen Shot 2023-07-09 at 3 28 08 PM](https://github.com/transitmatters/t-performance-dash/assets/1361408/7d111449-382a-4a29-b6b1-2e3c4f64e4ed) |

feat: add travel time copy

---

common/components/inputs/DateSelection/DatePickers.tsx
common/components/inputs/DateSelection/DateSelection.tsx
common/components/widgets/StationSelectorWidget.tsx
common/utils/router.tsx

#712
- Handles default loading values to not pollute history, but preserves date changes done by the user in the history
Visit pages, hit back, make sure things feel natural and you can actually go back

Fixes back navigation to account for date changes

---

modules/slowzones/SystemSlowZonesDetails.tsx

The x axis labels were overlapping the border of the chart.
Fixes this.

bug with sz system chart

---

common/api/hooks/ridership.ts
common/api/hooks/tripmetrics.ts

#705 
Onlly show values for weeks which are completed on landing.

Only show full weeks on landing

---

common/components/inputs/StationSelector.tsx

Fix #744 
Shrink the selector. Ideal future solution would be to make sure it is on top of top nav bar.
Open on the smallest phone you own.

Shrink station selector on mobile

---

common/constants/baselines.ts
modules/headways/HeadwaysDetails.tsx
modules/headways/charts/HeadwaysHistogramWrapper.tsx
modules/tripexplorer/SubwayTripGraphs.tsx

Forgot to add the headways histogram back.
Adds headways histogram back.
Removing the grid in #748 which makes the whitespace at the botom go away.

add histogram back

---

server/frontend-cfn.json

V3 relied on React Router to handle different URLs, and that worked because S3 returned the SPA for any request path. Next is more of a good citizen, in that it's generating actual files that are being served by S3/CloudFront. For that reason, we want the status code for 404s to ACTUALLY BE 404! :) Finally!
We're changing the 404 ResponseCode from 200 to 404. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudfront-distribution-customerrorresponse.html
Previous behavior:
```
prestonmueller@Preston14 ~ $ curl -sI https://dashboard-beta.labs.transitmatters.org/this_doesnt_exist | head -n 1
HTTP/1.1 200 OK
```
Behavior after this is merged (anticipated);
```
prestonmueller@Preston14 ~ $ curl -sI https://dashboard-beta.labs.transitmatters.org/this_doesnt_exist …
```

Remove v3 relic of 404s being a lie because of react router

---

common/components/maps/LineMap.stories.tsx
common/components/maps/LineMap.tsx
common/components/maps/useDiagramCoordinates.ts
common/utils/time.tsx
modules/slowzones/map/DirectionIndicator.tsx
modules/slowzones/map/SlowSegmentLabel.tsx
modules/slowzones/map/SlowZonesMap.tsx

The time labels for Slow Zones map segments were previously rendered with the `<foreignobject>` SVG element, which doesn't really work in Safari. This change renders them in pure SVG.
SVG layout is pretty manual work and it was easiest to resort to Unicode characters for the directional arrows. I found that the ones that work best (i.e. have no weird subpixel glitches) are these chevron ones:
On mobile, though, we'll get a slightly different arrow look:
Visit `/red/slowzones` in desktop/mobile Safari and check that these elements render properly.

fix: Render SZ segment labels properly in Safari

---

common/components/general/ButtonGroup.tsx
common/types/ridership.ts
copy/landingCopy.tsx
modules/landing/charts/LandingPageChart.tsx
modules/ridership/RidershipGraphWrapper.tsx
modules/service/PercentageServiceGraph.tsx
modules/service/PercentageServiceGraphWrapper.tsx
modules/service/ServiceDetails.tsx
modules/service/utils/utils.ts
modules/slowzones/map/SlowZonesTooltip.tsx

Our "baselines" are just peaks, so I've renamed them as such.
#547 
Change baseline -> peak in all strings
Make sure "baseline" isn't used anywhere.

baseline -> Peak

---

deploy.sh
v3_to_v4_slash_trick/trick.html

Add v3/v4 file trick to make it OK that V3 paths don't have trailing slashes. Fixes #750 
- Add HTML pages (with no extension, but they have a Content type set, so it's OK!) at /rapidtransit, /bus, and /slowzones that have the sole purpose of redirecting to the trailing slash equivalent.
https://dashboard-beta.labs.transitmatters.org/rapidtransit?config=Red,70067,70071,2023-07-15,
should look the same as the v3 equiv:
https://dashboard.transitmatters.org/rapidtransit?config=Red,70067,70071,2023-07-15,

Add v3/v4 file trick to make it OK that V3 paths don't have trailing slashes

---

modules/landing/Landing.tsx

V4 home page title adjustment

---

common/components/maps/LineMap.module.css
common/components/maps/LineMap.tsx
modules/slowzones/map/SlowZonesMap.tsx
modules/slowzones/map/SlowZonesTooltip.module.css
modules/slowzones/map/SlowZonesTooltip.tsx

Resolves #573 and #687
This changes moves the SZ tooltip to the left side of the map when there's more real estate for it there (e.g. on the Braintree branch). It also makes sure the tooltip is never hidden by the left-hand sidebar. I kept the tooltip beneath the mobile bottom controls, though — seems better; just scroll.
Check the tooltip rendering for the Red Line map on both desktop and mobile.

fix: Better SZ tooltip positioning

---

deploy.sh
server/frontend-cfn.json

Allow datadog to tell apart deploys
https://docs.datadoghq.com/tracing/services/deployment_tracking/
- Adds git id to deployment env variables

Allow datadog to tell apart deploys

---

common/utils/middleware.ts

Fix https://github.com/transitmatters/t-performance-dash/issues/789 (see that issue for details)
https://dashboard.transitmatters.org/slowzones?startDate=2022-08-01 should work with an end date of today

(v4) Fix v3 slowzones links with no end date

---

deploy.sh
server/frontend-cfn.json

Have deployment tracking show a more accurate deploy id
This value is only used by Datadog to track deployed version. In v4 we don't currently show this in the UI (we can change that, but for now this isn't useful)
Show a version like: `4.0-2-gbab466b2` or `4.0` when deploying a tagged commit

Show better git tagging in deployment script

---

deploy.sh
server/frontend-cfn.json

This morning we couldn't figure out which API Gateway entity belonged to which hostname when we were trying to figure out what was wrong with the stacks.
This sets the API Gateway title to the backend hostname, which makes this suck less.
These should be the hostname instead of `data-dashboard`: https://us-east-1.console.aws.amazon.com/apigateway/main/apis?region=us-east-1

Set API Gateway name to the backend hostname, for debugging ease

---

.github/workflows/healthcheck.yml

healthcheck machine broke
Updates the API endpoint
```bash
curl --fail-with-body https://dashboard-api.labs.transitmatters.org/api/healthcheck
```

hotfix: github action healthcheck

---

copy/landingCopy.tsx
modules/landing/LandingChartDiv.tsx
modules/landing/LandingChartWidget.tsx
modules/landing/LandingCharts.tsx
modules/landing/charts/LandingPageChart.tsx
modules/landing/charts/OverallRidershipChart.tsx
modules/landing/charts/OverallServiceChart.tsx
modules/landing/charts/OverallSpeedChart.tsx

#819 #826 
Landing page graphs weren't too screenshot-friendly.
I had some struggles getting the size perfectly right, something to do with ChartJS charts not resizing... If anyone wants to work on that lmk, but I think it's okay as is. Check out the `lg` breakpoint to see what I mean (1024px). 
**Before**
**Aftter**
Check out on various screen sizes.

Landing chart work

---

modules/landing/charts/LandingPageChart.tsx

The landing page chart tooltip titles were `week of <start date>`.
This made the data seem older than it was and like we weren't keeping it up to date.
Change the title to `<start date> - <end date>`
**Before**
**After**
Look at chart tooltip titles.

Change landing page widget title

---

modules/tripexplorer/BusTripGraphs.tsx

Bus Travel times by hour was missing in new dashboards.
Add it back
Check out various routes and date configurations

Bus TT by hour

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/workflows/healthcheck.yml
common/types/basicWidgets.tsx
modules/ridership/RidershipGraph.tsx
modules/service/ServiceGraph.tsx
modules/speed/SpeedGraph.tsx

This PR makes some stylistic suggestions to the chart formatting and coloring as well as some minor tweaks to the Bug Template and Healthcheck action
- Clarified that `Version` in Bug Template referred to `Browser Version`
- Users can now trigger `healthcheck` action on demand
- Updated Historic Maximums to include commas to match labels on vertical axis
- Changed `trips` to `Trips` in Service graph to match other graphs' vertical axis
- Changed `Trips` in Ridership graph to `Riders`
- Added descriptor of Historic Maximum to all graphs for readability and consistency with the horizontal axis
- Made `MPH` box background more white than gray to match the graph background
Deploy this PR locally

Tweaks to chart format and colors

---

modules/ridership/RidershipGraphWrapper.tsx
modules/ridership/utils/utils.ts
modules/service/ServiceGraphWrapper.tsx
modules/speed/SpeedGraphWrapper.tsx

1. Fixing this #834 
2. Adding max to ridership widget carousel
1)
**Before**
**After**
2)
Added max to ridership widgets:

Ridership max widget + small fix.

---

modules/slowzones/charts/LineSegments.tsx

A link to a slowzone on the multi-day view should show trailing context to make the extent of the slowzone clear:

Extend slowzone segment link to include 7 days of trailing data.

---

modules/slowzones/map/SlowZonesTooltip.tsx
modules/slowzones/map/segment.ts

Resolves #764 
Test plan:
- Visit `/red/slowzones/?startDate=2022-06-01&endDate=2022-09-05` and verify that only a few sz are shown on the map
- Return to today and verify that there are a lot more 😢

fix: Only add slow zones to map that existed at currently selected `endDate`

---

common/components/maps/diagrams/lines.ts

[869] Fix overlap in Red Line slow zone chart

---

modules/slowzones/map/SlowZonesMap.tsx

When using `TODAY` data, get the opacity correct
Uses `latest_delay` for opacity when showing today's data

Fixing color opacity on map for today

---

deploy.sh
modules/slowzones/SystemSlowZonesDetails.tsx

Systemwide page should match those of the individual lines, and I want @akh4rf's hard work to not be buried under all the T's slow zone segments :smile: 
Just a position swap
Build the dashboard locally with this branch

Swapped position of Line Map and Segment Chart for systemwide Slow Zone view

---

common/components/inputs/StationSelector.tsx

https://github.com/transitmatters/t-performance-dash/issues/861
The previous `position: fixed` caused unexpected behavior during scrolling due to a `transform` applied to its containing element as part of the animation that happens when you open the dropdown menu. This is due to an interesting quirk of CSS that you can read about [here](https://meyerweb.com/eric/thoughts/2011/09/12/un-fixing-fixed-elements-with-css-transforms/)
Changed `position: fixed` to `position: absolute` for the dropdown menu container to address scrolling issues. By switching to `position: absolute`, the element is now fixed with respect to its nearest positioned ancestor's context without being affected by `transform`s.
Tested the change across different browsers and mobile views to validate the fix's …

fix scrolling issue in dropdown menu

---

modules/service/utils/utils.ts

Service chart is crashing
Looks like there's sometimes a mismatch in the length of the predicted and actual service values. Don't assume they are the same length.
Load the Red Line overview page

fix: Bad property access crashes service chart

---

.vscode/settings.json
common/components/graphics/styles/spinnerFillColor.ts
common/components/nav/CommuterRailDropdown.tsx
common/components/nav/CommuterRailRouteSelection.tsx
common/components/nav/CommuterRailSection.tsx
common/components/nav/MenuDropdown.tsx
common/components/widgets/MiniWidgetCreator.tsx
common/components/widgets/internal/UnitText.tsx
common/constants/colors.ts
common/constants/lines.ts
common/constants/pages.ts
common/constants/stations.ts
common/state/defaults/dateDefaults.ts
common/styles/general.ts
common/types/lines.ts
modules/landing/LandingChartDiv.tsx
modules/speed/constants/speeds.ts
tailwind.config.js

Prepare to add commuter rail to the dashboard in the future, by adding the colors and the sidebar selector ready to go
- Adding commuter rail keys and colors
- Adding a commuter rail tab to codebase, but not adding it to the UI yet
- Fixes Bus sidebar icon
There's nothing currently to test. Nothing is set to display

Add commuter rail colors and cleanup

---

common/types/charts.ts
common/types/dataPoints.ts
modules/headways/charts/HeadwaysHistogram.tsx

Closes https://github.com/transitmatters/t-performance-dash/issues/800
I experimented with showing difference from the benchmark instead, but it ended up being a little bit confusing in my opinion. As an alternative, I made the tooltip display the benchmark time for more context. Let me know what you think.
Navigate to trip explorer page for all lines and ensure that the headways distribution chart displays correctly

feat: headways historgram improvements

---

common/constants/dates.ts
server/chalicelib/constants.py

November 2023 Bus data
- Bumps max bus date to Nov 2023
- Removed unused python variable

Adding bus data for Nov 2023

---

common/components/nav/SubwayDropdown.tsx
common/types/lines.ts
pages/[line]/slowzones.tsx

Closes https://github.com/transitmatters/t-performance-dash/issues/921
I went with just removing the slow zones tab for the green line. This seems like a better temporary fix until we have stuff ready for that page 
Navigate to http://localhost:3000/green/slowzones/?startDate=2022-12-28&endDate=2023-12-28 and verify a 404. Verify that the slow zones tab for the green line is gone

fix(slow_zones): make green line slow zones page unselectable

---

modules/tripexplorer/SubwayTripGraphs.tsx

After merging https://github.com/transitmatters/t-performance-dash/pull/909, I noticed that the distances from the GLX stations inbound weren't quite right 🤦 .  I missed this because they're fine in the outbound direction. Example below. It looks like I'll have to manually correct those. All of the other distances look good. For now, I think it's best to just disable this feature for the green line until then. 
Disable the speed between stations feature for GL trip explorer only until we can fix it 
Verify there is no speed selector for the Green Line trip graphs

fix(trip-explorer): disable speed between stations for green line

---

common/components/notices/BusDataNotice.tsx
common/components/notices/GobbleDataNotice.tsx
common/components/notices/SameDayNotice.tsx
common/components/notices/TerminusNotice.tsx
common/components/widgets/WidgetPage.tsx
common/constants/dates.ts
modules/ridership/RidershipDetails.tsx
modules/ridership/RidershipWidget.tsx
modules/tripexplorer/TripExplorer.tsx
server/chalicelib/s3.py
server/chalicelib/s3_historical.py
server/rapid/process_events.py
server/rapid/setup_rapid_input.sh
server/scripts/generate_line_files.py
styles/dashboard.css

Get the app in a state ready for gobble data
Only shows gobble data when manually navigating to a bus url with a date past the current maximum.
Nobody can reach gobble data through the UI, but could by changing `startDate=2024-01-22` if they wanted to.
Adds a new warning banner to the bottom explaining that we parsed this data ourselves

Shows gobble data in the dashboard

---

server/chalicelib/s3.py
server/chalicelib/s3_historical.py

Things work a lot faster when we don't load the same file 30 times for a month...
- Switches back from `date_range` to `month_range`

Fixing aggregate query performance

---

common/components/charts/ChartPageDiv.tsx
common/components/notices/BetaDataNotice.tsx
common/components/notices/SameDayNotice.tsx
common/constants/dates.ts
common/state/defaults/dateDefaults.ts
modules/landing/LineButton.tsx
modules/tripexplorer/TripExplorer.tsx
server/chalicelib/s3.py

Release gobble bus data to the masses!
Releases day of bus data and switches bus to use the same date presets as rapid transit
Confirm that there is live data for all bus routes
Confirm that data before Feb 29th 2024 doesn't show the beta warning
Confirm that aggregates and single dates all still work for bus data

Live Bus Data Beta Release

---

common/constants/dates.ts
server/chalicelib/date_utils.py

Monthly data for march is now available
Bumps monthly bus and rapid data to March

Bump monthly data to March 31st 2024

---

README.md
modules/predictions/PredictionsDetails.tsx

Just some additional clarity for users, wrt both changes
- Adds additional explainer text about where we get our data about predictions
- Adds release badge to README

Add additional explainer text around prediction data delivery

---

common/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
common/utils/array.ts
modules/service/ServiceGraph.tsx

I've noticed that the scheduled/delivered trip counts graph is getting out of sync. It turns out that we are missing a few data points for each line in the `DeliveredTripMetricsWeekly` table, which is causing the `delivered` array for a given date range to be a little shorter than the `scheduled` one. We should backfill these values, but in the meantime, I've added some code to make sure that the data points on those graphs are always aligned by day. This results in some "holes" in the graph. Maybe there was shuttling that should appear here?
Long term I there should be a single API that returns both scheduled and delivered trip counts in one shot, like `/api/service_hours` does.
Before:
After:
With "Past Year" time range selected, click through the Overview pages for each rapid transit …

Fix: Align scheduled/delivered trip counts

---

common/components/charts/ByHourHistogram/ByHourHistogram.tsx
common/components/charts/TimeSeriesChart/TimeSeriesChart.tsx
modules/service/DailyServiceHistogram.tsx

Ensuring service data is easy to read, and ensures our charts are watermarked
Fixes #1006 
Adding missing watermarks, mobile fixes and headway calcs

Service page improvements

---

common/types/delays.ts
modules/delays/charts/DelayBreakdownGraph.tsx
modules/delays/charts/DelayByCategoryGraph.tsx
modules/delays/charts/utils.ts

Delay categories are only useful if there's delays, only show when more than 0m of delay
Cleans up the page
Fixes #1014 
- Filters out 0m delay categories from the charts
- Adds the two new categories being added in the new data-ingestion PR

Only show delays with more than 0m

---

common/api/slowzones.ts
modules/slowzones/SlowZonesDetails.tsx
modules/slowzones/SlowZonesWidget.tsx
modules/slowzones/SystemSlowZonesDetails.tsx
modules/slowzones/map/SlowSegmentLabel.module.css
modules/slowzones/map/SlowZonesMap.stories.tsx
modules/slowzones/map/SlowZonesMap.tsx
modules/slowzones/map/SlowZonesTooltip.module.css
modules/slowzones/map/segment.ts
server/chalicelib/data_funcs.py

Now that there are 0s of slowzones, the map needs to read the `updated_on` date, not the latest slowzone date
Fixes usage of new slowzone format

Fix slowzone date parsing in map

---

common/components/notices/BetaSlowZoneDataNotice.tsx

We only need the beta warning on Green line data

Hide beta warning on slow zones other than GL

---

common/types/lines.ts
modules/landing/utils.ts

We don't need to display Mattapan on the landing charts, they can get confusing mixed in with the red line
- Excludes Mattapan line from landing graphs

Exclude the Mattapan line from landing graphs

---

common/constants/charts.ts
modules/landing/charts/OverallRidershipChart.tsx
modules/landing/charts/OverallServiceChart.tsx
modules/landing/charts/OverallSpeedChart.tsx
modules/landing/utils.ts

I have been noticing missing data labels on the landing pages. See below:
**Expected: **
The issue is that the labels for the chart were naively generated under the assumption that all weeks would have data for every line (my fault, I wrote this code). So it only looks at red line data to generate the data labels. 
So it looks at the return trip_metrics json file and uses that to generate the labels. see here: https://dashboard.transitmatters.org/static/landing/trip_metrics.json
Currently, there was no data for the week 2024-11-18 in the dataset for the red line (another possible fix would be to generate empty data for weekly aggregates rather than exclude the data).
This caused the labels for the data to be misaligned and causes issues not only with the missing labels, but also all of …

Fix landing chart data labels

---

common/constants/cr_constants/cr-fairmount.json
common/constants/cr_constants/cr-fitchburg.json
common/constants/cr_constants/cr-franklin.json
common/constants/cr_constants/cr-greenbush.json
common/constants/cr_constants/cr-kingston.json
common/constants/cr_constants/cr-middleborough.json
common/constants/cr_constants/cr-needham.json
common/constants/cr_constants/cr-newburyport.json
common/constants/cr_constants/cr-providence.json
common/constants/cr_constants/cr-worcester.json
server/scripts/generate_line_files.py

Ensure that when updating CR manifests, we have smaller diffs in the future
- Adds a sort option to CR stop ids

Sort stop ids so we have consistent updates

---

common/constants/dates.ts
server/chalicelib/date_utils.py

Use historic official file data when available
Use historic bus data, up to April 30

Bump historic usage to April

---

modules/speed/charts/SpeedBetweenStationsAggregateChart.tsx
modules/traveltimes/charts/TravelTimesAggregateChart.tsx

Per #1038 Tooltip times are 24-hour formatted, but with an AM/PM indicator on the "travel times by hour" chart.
This PR fixes the time format so that the times are formatted as 12-hour instead of 24. 
Changed H:mm aaaa to h:mm aaaa on TravelTimesAggregateChart which was the chart that prompted the issue. I also changed it on SpeedBetweenStationsAggregateChart however we don't seem to show the time on that tooltip. 
Start local environment and navigate to one of the lines or bus, then select "multi-day trips". Under the Travel times by hour chart hover over a datapoint after 1pm or so. If there is no data available, modify to an earlier date from the default Today value to ensure data in the afternoon populates.

Updated time format to 12hr (#1038)

---

common/constants/bus_constants/SL1-SL2-SL3-SLW.json

Fixes the SLW route to show SLW instead of 746_
Spin up a dev server, navigate to the silver line and check the dropdown

Replace Branch 746_ with SLW

---

modules/serviceAndRidership/LineCard/TphChart.tsx
modules/serviceAndRidership/LineGrid/LineGrid.tsx

Things were looking a little silly on my giant monitor:
Much more manageable now:
Visit `/system/ridership` and check that line cards look good at all viewport sizes

Improve ridership dashboard styling for very large viewports
